[build]
  command = "pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://ddangkong.netlify.app/*"
  to = "https://ddangkong.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.ddangkong.xyz/*"
  to = "https://ddangkong.xyz/:splat"
  status = 301
  force = true
