import "./globals.css";
import type { Metadata } from "next";
import Navigation from "@/components/@layout/Navigation";

export const metadata: Metadata = {
  title: "심심풀이 땅콩",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Navigation />
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
